### ISSUE TITLE
More Semantic Boundary

### ISSUE THREAD

**Issue by harmonic-lqw** [L-YeZhu/BoundaryDiffusion#1]
Your work is very nice. Can you please give more semantic boundaries like makeup and young? Or please give the file: '/n/fs/yz-diff/inversion/list_attr_celeba.txt' to help me find the semantic boundary. Thank you!

**Comment by ZhouCX117** [comment]
Hi, I think the file can be found 'https://github.com/taki0112/StarGAN-Tensorflow/blob/master/dataset/celebA/list_attr_celeba.txt'.
