### ISSUE TITLE
I cannot download the pretrained models 

### ISSUE THREAD

**Issue by AlfaranoAndrea** [L-YeZhu/BoundaryDiffusion#2]
I am attempting to reproduce your results, but I am encountering an issue with the automatic weight download. The files at URLs like https://image-editing-test-12345.s3-us-west-2.amazonaws.com/checkpoints/celeba_hq.ckpt appear to be inaccessible. Could you please provide alternative links or instructions for obtaining the required weights?

**Comment by L-YeZhu** [comment]
Try [this link](https://drive.google.com/file/d/1nvZBEPlXBKle2ib-X6Bsfyxt1l__4CNj/view?usp=share_link) for the pre-trained DDPM on CelebA.
